
---

# ⚙️ GitHub Workflows

### `.github/workflows/simple-ci.yml`
```yaml
name: Simple Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-docker-demo .

      - name: Run container
        run: docker run -d -p 5000:5000 --name flask-test flask-docker-demo

      - name: Wait for container
        run: sleep 5

      - name: Curl test
        run: curl -fsS http://localhost:5000/
